// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT6vB-rGwkOUktMBU72AO1TJGFjRg7wkY',
    appId: '1:1061772311330:web:53c3e0183bd9206b97437b',
    messagingSenderId: '1061772311330',
    projectId: 'vibhub-cba0d',
    authDomain: 'vibhub-cba0d.firebaseapp.com',
    storageBucket: 'vibhub-cba0d.appspot.com',
    measurementId: 'G-S1Z95DHTXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFQ0lry4e1yipDoGsaPH2hwvBT7A1xI60',
    appId: '1:1061772311330:android:6219e0ba2d552b6f97437b',
    messagingSenderId: '1061772311330',
    projectId: 'vibhub-cba0d',
    storageBucket: 'vibhub-cba0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB14Ru0XYMI650G6d6igtANw2IDa6Ztieo',
    appId: '1:1061772311330:ios:41098d6b92d6e47d97437b',
    messagingSenderId: '1061772311330',
    projectId: 'vibhub-cba0d',
    storageBucket: 'vibhub-cba0d.appspot.com',
    iosBundleId: 'com.example.vibhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB14Ru0XYMI650G6d6igtANw2IDa6Ztieo',
    appId: '1:1061772311330:ios:41098d6b92d6e47d97437b',
    messagingSenderId: '1061772311330',
    projectId: 'vibhub-cba0d',
    storageBucket: 'vibhub-cba0d.appspot.com',
    iosBundleId: 'com.example.vibhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT6vB-rGwkOUktMBU72AO1TJGFjRg7wkY',
    appId: '1:1061772311330:web:c7322e729fc9f8ff97437b',
    messagingSenderId: '1061772311330',
    projectId: 'vibhub-cba0d',
    authDomain: 'vibhub-cba0d.firebaseapp.com',
    storageBucket: 'vibhub-cba0d.appspot.com',
    measurementId: 'G-2DE2SMB74Y',
  );
}
